name: Deploy to Cloudflare Pages

on:
  push:
    branches:
      - main
      - master
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    name: Deploy
    steps:
      - uses: actions/checkout@v4

      - name: Install Bun
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest

      - name: Cache dependencies
        uses: actions/cache@v3
        with:
          path: |
            ~/.bun/install/cache
            node_modules
          key: ${{ runner.os }}-bun-${{ hashFiles('**/bun.lockb') }}
          restore-keys: |
            ${{ runner.os }}-bun-

      - name: Install dependencies
        run: bun install --frozen-lockfile

      - name: Create environment file
        run: |
          cat << EOF > .env
          AUTH_TRUST_HOST=${{ secrets.AUTH_SECRET }}
          AUTH_SECRET=${{ vars.AUTH_TRUST_HOST }}
          AUTHENTIK_ISSUER=${{ vars.AUTHENTIK_ISSUER }}
          AUTHENTIK_CLIENT_ID=${{ vars.AUTHENTIK_CLIENT_ID }}
          AUTHENTIK_CLIENT_SECRET=${{ secrets.AUTHENTIK_CLIENT_SECRET }}
          NOTION_API_KEY=${{ secrets.NOTION_API_KEY }}
          NOTION_DATABASE_ID=${{ vars.NOTION_DATABASE_ID }}
          EOF

      - name: Build site
        run: bun run build
        env:
          NODE_ENV: production

      - name: Deploy to Cloudflare Pages
        uses: cloudflare/wrangler-action@v3
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ vars.CLOUDFLARE_ACCOUNT_ID }}
          command: pages deploy dist --project-name=homepage
          packageManager: bun
